# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdexec/api/proto/sql_cmd_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from cmdexec.clients.python.api import messages_pb2 as cmdexec_dot_api_dot_proto_dot_messages__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='cmdexec/api/proto/sql_cmd_service.proto',
    package='com.databricks.cmdexec',
    syntax='proto2',
    serialized_options=b'\n*com.databricks.cmdexec.sql_command_service\240\001\001',
    create_key=_descriptor._internal_create_key,
    serialized_pb=
    b'\n\'cmdexec/api/proto/sql_cmd_service.proto\x12\x16\x63om.databricks.cmdexec\x1a cmdexec/api/proto/messages.proto2\xaa\x06\n\x11SqlCommandService\x12\x66\n\x0bOpenSession\x12*.com.databricks.cmdexec.OpenSessionRequest\x1a+.com.databricks.cmdexec.OpenSessionResponse\x12i\n\x0c\x43loseSession\x12+.com.databricks.cmdexec.CloseSessionRequest\x1a,.com.databricks.cmdexec.CloseSessionResponse\x12o\n\x0eGetSessionInfo\x12-.com.databricks.cmdexec.GetSessionInfoRequest\x1a..com.databricks.cmdexec.GetSessionInfoResponse\x12o\n\x0e\x45xecuteCommand\x12-.com.databricks.cmdexec.ExecuteCommandRequest\x1a..com.databricks.cmdexec.ExecuteCommandResponse\x12u\n\x10GetCommandStatus\x12/.com.databricks.cmdexec.GetCommandStatusRequest\x1a\x30.com.databricks.cmdexec.GetCommandStatusResponse\x12~\n\x13\x46\x65tchCommandResults\x12\x32.com.databricks.cmdexec.FetchCommandResultsRequest\x1a\x33.com.databricks.cmdexec.FetchCommandResultsResponse\x12i\n\x0c\x43loseCommand\x12+.com.databricks.cmdexec.CloseCommandRequest\x1a,.com.databricks.cmdexec.CloseCommandResponseB/\n*com.databricks.cmdexec.sql_command_service\xa0\x01\x01',
    dependencies=[
        cmdexec_dot_api_dot_proto_dot_messages__pb2.DESCRIPTOR,
    ])

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DESCRIPTOR._options = None

_SQLCOMMANDSERVICE = _descriptor.ServiceDescriptor(
    name='SqlCommandService',
    full_name='com.databricks.cmdexec.SqlCommandService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=102,
    serialized_end=912,
    methods=[
        _descriptor.MethodDescriptor(
            name='OpenSession',
            full_name='com.databricks.cmdexec.SqlCommandService.OpenSession',
            index=0,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._OPENSESSIONREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._OPENSESSIONRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='CloseSession',
            full_name='com.databricks.cmdexec.SqlCommandService.CloseSession',
            index=1,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._CLOSESESSIONREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._CLOSESESSIONRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='GetSessionInfo',
            full_name='com.databricks.cmdexec.SqlCommandService.GetSessionInfo',
            index=2,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._GETSESSIONINFOREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._GETSESSIONINFORESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='ExecuteCommand',
            full_name='com.databricks.cmdexec.SqlCommandService.ExecuteCommand',
            index=3,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._EXECUTECOMMANDREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._EXECUTECOMMANDRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='GetCommandStatus',
            full_name='com.databricks.cmdexec.SqlCommandService.GetCommandStatus',
            index=4,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._GETCOMMANDSTATUSREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._GETCOMMANDSTATUSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='FetchCommandResults',
            full_name='com.databricks.cmdexec.SqlCommandService.FetchCommandResults',
            index=5,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._FETCHCOMMANDRESULTSREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._FETCHCOMMANDRESULTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='CloseCommand',
            full_name='com.databricks.cmdexec.SqlCommandService.CloseCommand',
            index=6,
            containing_service=None,
            input_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._CLOSECOMMANDREQUEST,
            output_type=cmdexec_dot_api_dot_proto_dot_messages__pb2._CLOSECOMMANDRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SQLCOMMANDSERVICE)

DESCRIPTOR.services_by_name['SqlCommandService'] = _SQLCOMMANDSERVICE

# @@protoc_insertion_point(module_scope)
