name: Code Quality Checks
on:
  push:
    branches:
      - PECO-1803/connector-split
  pull_request:
    branches:
      - PECO-1803/connector-split
jobs:
  validate-connector-core:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          target_path: "databricks_sql_connector_core"
          run_test: true

