name: DCO Check

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DCO
        id: dco-check
        uses: tisonkun/actions-dco@6d1f8a197db1b04df1769707b46b9366b1eca902 # v1.1
      - name: Comment about DCO status
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thanks for your contribution! To satisfy the DCO policy in our \
              [contributing guide](https://github.com/databricks/databricks-sql-python/blob/main/CONTRIBUTING.md) \
              every commit message must include a sign-off message. One or more of your commits is missing this message. \
              You can reword previous commit messages with an interactive rebase (\`git rebase -i main\`).`
            })
