name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  run-non-telemetry-tests:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    environment: azure-prod
    env:
      DATABRICKS_SERVER_HOSTNAME: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.TEST_PECO_WAREHOUSE_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CATALOG: peco
      DATABRICKS_USER: ${{ secrets.TEST_PECO_SP_ID }}
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Kerberos system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.10"
          install-args: "--all-extras"
      - name: Run non-telemetry e2e tests
        run: |
          poetry run python -m pytest tests/e2e \
            --ignore=tests/e2e/test_telemetry_e2e.py \
            --ignore=tests/e2e/test_concurrent_telemetry.py \
            -n auto

  run-telemetry-tests:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    needs: run-non-telemetry-tests
    environment: azure-prod
    env:
      DATABRICKS_SERVER_HOSTNAME: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.TEST_PECO_WAREHOUSE_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CATALOG: peco
      DATABRICKS_USER: ${{ secrets.TEST_PECO_SP_ID }}
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.10"
          install-args: "--all-extras"
      - name: Run telemetry tests in isolation
        run: |
          poetry run python -m pytest tests/e2e/test_concurrent_telemetry.py \
            -n auto --dist=loadgroup -v
