name: Notify DCO Failure

on:
  pull_request_target:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/notify-dco-failure.js`
            );
            script({ context, github });